### ISSUE TITLE
Zeros appended to WHOI Micromodem messages

### ISSUE THREAD

**Issue by jturner314-nrl** [GobySoft/goby3#286]
Commit d29775c45869486125a7e484d7d860c9019ceea7 changed the WHOI Micromodem driver to append zeros to fill up every frame. While this may be fine for DCCL messages, this makes it such that the driver cannot be used with a custom message encoding/decoding (not DCCL) which depends on acomms preserving the length of the message. For example, a variable-length array could be encoded by concatenating the encodings for the individual elements. However, this depends on the length being accurately preserved; if the driver adds zeros to the end, then the resulting decoded array will have extra elements full of zeros. Additionally, adding zeros to the end of every frame causes the acoustic transmissions to be longer than necessary.

The commit message for d29775c45869486125a7e484d7d860c9019ceea7 was "Workaround for partial frame bug in MM2". I don't know what the partial frame bug is/was; is the workaround still necessary? Testing with a few Micromodem 2s shows that, at least for single-frame messages, the modems transmit/receive messages without issues even without the extra trailing zeros.

**Comment by tsaubergine** [comment]
Hi -

This was a bug in early versions on MM2 firmware. Not sure exactly when it was fixed, but the workaround shouldn't be necessary for newer versions. I'd be happy to merge a PR with a boolean option for padding for zeros (and set the default so that it doesn't pad the frame with zeroes).

I'm pretty sure internally the frames are padded to the end and send in full regardless. Would be happy to be proven wrong, but I think that was part of the motivation for the FDP (flexible data packet).

**Comment by jturner314-nrl** [comment]
Okay, thanks. I'll submit a PR.

> I'm pretty sure internally the frames are padded to the end and send in full regardless. Would be happy to be proven wrong, but I think that was part of the motivation for the FDP (flexible data packet).

The Micromodem may internally add its own padding in the acoustic transmission; I'm not sure. However, I did observe that after disabling Goby's padding in the transmitted messages (in `$CCTXD`), the messages received on the other modem (in `$CARXD`) had no padding. So, if the Micromodem adds its own padding, it  must also be transmitting the message length and using that to strip off the padding on the receive side.
