### ISSUE TITLE
Scanning for log entry magic is incorrect

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#32]
```
                while(magic_read != magic_)
                {
                    while(s->peek() != magic_[0])
                    {
                        ++discarded;
                        s->get();
                    }
                    s->read(&magic_read[0], magic_.size());
                }
```

The stream `GGBY3` I think will be parsed incorrectly:

1. Peek `G`, break out of the inner loop
2. Read `GGBY`, do *not* break out of the outer loop
3. Peek `3`, do *not* break out of the inner loop
4. Raise EOF exception

**Comment by tsaubergine** [comment]
This may be the case, but it would be pretty rare since you would need to have:
1. An invalid message in the log so we're seeking past corruption; PLUS
2. The (corrupt) message ends in 'G'.

Happy to take a fix if you have one. And, if so, please add a breaking case first to https://github.com/GobySoft/goby3/tree/3.0/src/test/middleware/log

-Toby
