### ISSUE TITLE
Extend publish API for sending a message without a payload

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#56]
This works:

    interthread().publish<groups::nav>(std::shared_ptr<void>(nullptr));

But it would be more elegant like this:

    interthread().publish<groups::nav>();

The use case is where you just want to signal to another thread that it should kick off some task, but there's no specific payload content you need to include.

**Comment by tsaubergine** [comment]
This was added back in 2020 at https://github.com/GobySoft/goby3/commit/a798dd136#diff-69682a296f4357877833db57668027cdbfe5389277e043c2f7fb99a3e460517bR126

```
interthread().publish_empty<groups::nav>()
```

The use of `publish_empty` was chosen rather than an overload of `publish` so that the empty publication would have to be explicitly chosen by the developer. This means the compiler can still catch the case where the publication variable is inadvertently omitted.
